package rules.nutrition;

import live.healthy.facts.model.user.User;
import live.healthy.facts.dto.PlanDto;


rule "amount of calories needed for MAINTAIN_WEIGHT"
    when
        $planDto : PlanDto(goal == "MAINTAIN_WEIGHT")
        $user : User()
    then
        $planDto.setBmrPercentNeeded(1.0);
        update($planDto);
        System.out.println("You should be taking 100% of amount of calories that your body metabolism rate is.");
end
/****************      MALE WEIGHT LOSS    ******************/

rule "amount of calories needed for WEIGHT_LOSS - male"
    activation-group "weight loss male"
    salience 3
    when
        $planDto : PlanDto(goal == "WEIGHT_LOSS")
        $user : User(sex == true)
    then
        $planDto.setBmrPercentNeeded(0.9);
        update($planDto);
        System.out.println("You should be taking 90% of amount of calories that your body metabolism rate is.");
end

rule "amount of calories needed for MILD_WEIGHT_LOSS - male"
    activation-group "weight loss male"
    salience 2
    when
        $planDto : PlanDto(goal == "MILD_WEIGHT_LOSS")
        $user : User(sex == true)
    then
        $planDto.setBmrPercentNeeded(0.79);
        update($planDto);
        System.out.println("You should be taking 79% of amount of calories that your body metabolism rate is.");
end

rule "amount of calories needed for EXTREME_WEIGHT_LOSS - male"
    activation-group "weight loss male"
    salience 1
    when
        $planDto : PlanDto(goal == "EXTREME_WEIGHT_LOSS")
        $user : User(sex == true)
    then
        $planDto.setBmrPercentNeeded(0.59);
        update($planDto);
        System.out.println("You should be taking 59% of amount of calories that your body metabolism rate is.");
end



/****************      FEMALE WEIGHT LOSS    ******************/


rule "amount of calories needed for WEIGHT_LOSS - female"
    when
        $planDto : PlanDto(goal == "WEIGHT_LOSS")
        $user : User(sex == false)
    then
        $planDto.setBmrPercentNeeded(0.89);
        update($planDto);
        System.out.println("You should be taking 89% of amount of calories that your body metabolism rate is.");
end

rule "amount of calories needed for MILD_WEIGHT_LOSS - female"
    when
        $planDto : PlanDto(goal == "MILD_WEIGHT_LOSS")
        $user : User(sex == false)
    then
        $planDto.setBmrPercentNeeded(0.77);
        update($planDto);
        System.out.println("You should be taking 77% of amount of calories that your body metabolism rate is.");
end

rule "amount of calories needed for EXTREME_WEIGHT_LOSS - female"
    when
        $planDto : PlanDto(goal == "EXTREME_WEIGHT_LOSS")
        $user : User(sex == false)
    then
        $planDto.setBmrPercentNeeded(0.54);
        update($planDto);
        System.out.println("You should be taking 54% of amount of calories that your body metabolism rate is.");
end




/************************* MALE WEIGHT GAIN ****************************/

rule "amount of calories needed for WEIGHT_GAIN - male"
    when
        $planDto : PlanDto(goal == "WEIGHT_GAIN")
        $user : User(sex == true)
    then
        $planDto.setBmrPercentNeeded(1.13);
        update($planDto);
        System.out.println("You should be taking 113% of amount of calories that your body metabolism rate is.");
end

rule "amount of calories needed for MILD_WEIGHT_GAIN - male"
    when
        $planDto : PlanDto(goal == "MILD_WEIGHT_GAIN")
        $user : User(sex == true)
    then
        $planDto.setBmrPercentNeeded(1.25);
        update($planDto);
        System.out.println("You should be taking 125% of amount of calories that your body metabolism rate is.");
end

rule "amount of calories needed for EXTREME_WEIGHT_GAIN - male"
    when
        $planDto : PlanDto(goal == "EXTREME_WEIGHT_GAIN")
        $user : User(sex == true)
    then
        $planDto.setBmrPercentNeeded(1.5);
        update($planDto);
        System.out.println("You should be taking 150% of amount of calories that your body metabolism rate is.");
end


/************************* FEMALE WEIGHT GAIN ****************************/

rule "amount of calories needed for WEIGHT_GAIN - female"
    when
        $planDto : PlanDto(goal == "WEIGHT_GAIN")
        $user : User(sex == false)
    then
        $planDto.setBmrPercentNeeded(1.14);
        update($planDto);
        System.out.println("You should be taking 114% of amount of calories that your body metabolism rate is.");
end

rule "amount of calories needed for MILD_WEIGHT_GAIN - female"
    when
        $planDto : PlanDto(goal == "MILD_WEIGHT_GAIN")
        $user : User(sex == false)
    then
        $planDto.setBmrPercentNeeded(1.28);
        update($planDto);
        System.out.println("You should be taking 128% of amount of calories that your body metabolism rate is.");
end

rule "amount of calories needed for EXTREME_WEIGHT_GAIN - female"
    when
        $planDto : PlanDto(goal == "EXTREME_WEIGHT_GAIN")
        $user : User(sex == false)
    then
        $planDto.setBmrPercentNeeded(1.56);
        update($planDto);
        System.out.println("You should be taking 156% of amount of calories that your body metabolism rate is.");
end





