package liveHealthy.nutrition;

import live.healthy.facts.model.user.User;
import live.healthy.facts.dto.CoefficientsDto;
import live.healthy.facts.BodyType.Type;
import live.healthy.facts.model.plan.NutritionPlan;

global Double idealBodyWeight;
global Double bodyMassIdx;
global Double bodyFatPercentage;
global Double weight;
global Integer age;
global String bodyType;
global Boolean sex;

rule "asd"
when
then
    System.out.println(bodyMassIdx);
 end
/**
*   ------------------------WEIGHT GAIN-------------------
*/
/***************************Level 1******************************/
rule "need to gain weight"
    when
        eval(bodyMassIdx < 25.0)
        and
        eval(weight < idealBodyWeight)
    then
        System.out.println("You should gain weight");
end


/***************************Level 2******************************/

rule "need to gain weight extreme way" extends "need to gain weight"
    when
        eval(bodyType == "ECTOMORPH")
    then
        System.out.println("You should gain weight with EXTREME_WEIGHT_GAIN");
end

rule "need to gain weight mild way" extends "need to gain weight"
    when
        eval(bodyType == "MESOMORPH")
    then
        System.out.println("You should gain weight with MILD_WEIGHT_GAIN");
end

rule "need to gain weight basic way" extends "need to gain weight"
    when
        eval(bodyType == "ENDOMORPH")
    then
        System.out.println("You should gain weight with WEIGHT_GAIN");
end



/***************************Level 3 Male******************************/

rule "need to gain with big fat level - teenager male" extends "need to gain weight extreme way"
    when
        eval(sex == true)
        and
        eval(age < 20) or eval(age == 20)
        and
        eval(bodyFatPercentage < 8.5)
    then
        System.out.println("You should gain weight with taking more fats");
end

rule "need to gain with big fat level - young male" extends "need to gain weight extreme way"
    when
        eval(sex == true)
        and
        eval(age > 20) or eval(age < 30) or eval(age == 30)
        and
        eval(bodyFatPercentage < 12.7)
    then
        System.out.println("You should gain weight with taking more fats");
end
rule "need to gain with big fat level - midAge male" extends "need to gain weight extreme way"
    when
        eval(sex == true)
        and
        eval(age > 30) or eval(age < 40) or eval(age == 40)
        and
        eval(bodyFatPercentage < 15.3)
    then
        System.out.println("You should gain weight with taking more fats");
end
rule "need to gain with big fat level - old male" extends "need to gain weight extreme way"
    when
        eval(sex == true)
        and
        eval(age > 40) or eval(age < 50) or eval(age == 50)
        and
        eval(bodyFatPercentage < 18.9)
    then
        System.out.println("You should gain weight with taking more fats");
end
rule "need to gain with big fat level - very old male" extends "need to gain weight extreme way"
    when
        eval(sex == true)
        and
        eval(age > 50)
        and
        eval(bodyFatPercentage < 20.9)
    then
        System.out.println("You should gain weight with taking more fats");
end
/**
*   -------------------WEIGHT LOSS-------------------
*/
/***************************Level 1******************************/

rule "need to lose weight"
    when
        eval(bodyMassIdx > 25.0)
        and
        eval(weight > idealBodyWeight)
    then
        NutritionPlan $nutritionPlan = new NutritionPlan();
        insert($nutritionPlan);
        System.out.println("You should lose some weight");
end



/***************************Level 2******************************/

rule "need to lose weight extreme way" extends "need to lose weight"
    when
        eval(bodyType == "ENDOMORPH")
    then
        System.out.println("You should lose weight with EXTREME_WEIGHT_LOSS");
end

rule "need to lose weight mild way" extends "need to lose weight"
    when
        eval(bodyType == "MESOMORPH")
    then
        System.out.println("You should lose weight with MILD_WEIGHT_LOSS");
end

rule "need to lose weight basic way" extends "need to lose weight"
    when
        eval(bodyType == "ECTOMORPH")
    then
        System.out.println("You should lose weight with WEIGHT_LOSS");
end


/***************************Level 3 Male******************************/

rule "need to lose with big fat loss - teenager male" extends "need to lose weight extreme way"
    when
        eval(sex == true)
        and
        eval(age <= 20) and
        eval(bodyFatPercentage > 8.5)
    then
        System.out.println("You should lose weight with taking less fats");
end
rule "need to lose with big fat loss - young male" extends "need to lose weight extreme way"
    when
        eval(sex == true)
        and
        eval(age <= 30) and
        eval(bodyFatPercentage > 12.7)
    then
        System.out.println("You should lose weight with taking less fats");
end
rule "need to lose with big fat loss - midAge male" extends "need to lose weight extreme way"
    when
        eval(sex == true)
        and
        eval(age <= 40) and
        eval(bodyFatPercentage > 15.3)
    then
        System.out.println("You should lose weight with taking less fats");
end

rule "need to lose with big fat loss - old male" extends "need to lose weight extreme way"
    when
        eval(sex == true)
        and
        eval(age <= 50) and
        eval(bodyFatPercentage > 18.9)
    then
        System.out.println("You should lose weight with taking less fats");
end
rule "need to lose with big fat loss - very old male" extends "need to lose weight extreme way"
    when
        eval(sex == true)
        and
        eval(age > 50) and
        eval(bodyFatPercentage > 21.0)
    then
        System.out.println("You should lose weight with taking less fats");
end