package rules.basic;

import live.healthy.facts.dto.BodyInfoDto;
import live.healthy.facts.dto.BodyTypeDto;
import live.healthy.facts.model.DailyActivity;


rule "Ectomorph - mesomorph"
    activation-group "body-type"
    salience 1
    when
        $bi: BodyInfoDto(shoulders in ("Narrower than my hips", "The same width as my hips"),
                        forearms in ("Small", "Average"),
                        bodyLook in ("Long and narrow", "Square and rugged"),
                        weightTendations in ("Have trouble gaining weight in the form of muscle or fat",
                         "I can gain and lose without too much of a struggle"),
                        bodyTendations in ("Stay skinny", "Stay lean, yet muscular")) and
        $bodyTypeDto: BodyTypeDto(type == "")
    then
        $bodyTypeDto.setType("ectomorph-mesomorph");
        $bodyTypeDto.setDescription("YOUR BODY IS BETWEEN AN ECTOMORPH AND A MESOMORPH.\n" +
                    "Ectomorph: You are good at processing carbohydrates into energy and" +
                        " your fast metabolism means that you burn off fat easily." +
                        " The downside is that you struggle to bulk up because your fast-twitch fibres are underdeveloped.\n" +
            	    "Mesomorph: You have the body type that finds it easiest to add new muscle and you don’t" +
                        " tend to store much body fat. Mesomorphs tend to take their naturally athletic builds for granted," +
                        " which can result in diluted workouts and poor diets. Keeping in peak physical condition is often" +
                        " tempered by a scattered approach to eating and training.");
        update($bodyTypeDto);
end

rule "Mesomorph - Endomorph"
    activation-group "body-type"
    salience 2
    when
        $bi: BodyInfoDto(shoulders in ("Wider than my hips", "The same width as my hips"),
                        forearms in ("Big", "Average"),
                        bodyLook in ("Round and soft", "Square and rugged"),
                        weightTendations in ("Gain weight easily, but find it hard to lose",
                         "I can gain and lose without too much of a struggle"),
                        bodyTendations in ("Carry a bit of extra fat", "Stay lean, yet muscular")) and
        $bodyTypeDto: BodyTypeDto(type == "")
    then
        $bodyTypeDto.setType("mesomorph-endomorph");
        $bodyTypeDto.setDescription("YOUR BODY IS BETWEEN AN MESOMORPH AND A ENDOMORPH.\n\n" +
                    "\tEndomorphs: Endomorphs are adept at storing fuel, with muscle and fat" +
                        "concentrated in the lower body. The endomorph is the hardest body type to have in terms" +
                        "of managing your weight and overall fitness.\n\n" +
            	    "\tMesomorph: You have the body type that finds it easiest to add new muscle and you don’t" +
                        " tend to store much body fat. Mesomorphs tend to take their naturally athletic builds for granted," +
                        " which can result in diluted workouts and poor diets. Keeping in peak physical condition is often" +
                        " tempered by a scattered approach to eating and training.");
        update($bodyTypeDto);
end


rule "Nonexistent type"
    activation-group "body-type"
    salience 1
    when
        $bodyTypeDto: BodyTypeDto(type == "")
    then
        $bodyTypeDto.setType("nonexistent");
        $bodyTypeDto.setDescription("Information about your body is contradictory. We cannot determine your type.");
        update($bodyTypeDto);
end